version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - HOST_NAME=localhost
      - USER_NAME=sa
      - PWD_NAME=etesp
      - DB_NAME=BancoHamburguer
      - SECRET_KEY=secret_key
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - HOST_NAME=root_password
      - USER_NAME=sa
      - PWD_NAME=etesp
      - DB_NAME=BancoHamburguer
      - SECRET_KEY=secret_key